#- name: Include passwords from secret.yaml
#  include_vars: secret.yml

- name: Install local dependencies
  local_action: command yum -y install python2-pyvmomi
  tags:
    - dep


- name: Clone a virtual machine from Template and customize
  vmware_guest:
    hostname: "{{ VMWARE_HOST }}"
    username: "{{ VMWARE_USER }}"
    password: "{{ VMWARE_PASSWORD }}"
    validate_certs: False
    datacenter: "{{ VMWARE_DATACENTER }}"
    cluster: "{{ VMWARE_CLUSTER }}"
    name: "{{ VMWARE_NAME }}"
    template: "{{ VMWARE_TEMPLATE }}"
    folder: "{{ VMWARE_FOLDER }}"
    networks:
    - name: "{{ VMWARE_NETWORK }}"
      ip: "{{ VMWARE_IP }}"
      netmask: "{{ VMWARE_NETMASK }}"
      gateway: "{{ VMWARE_GATEWAY }}"
#      device_type: vmxnet3
      dns_servers:
      - "{{ VMWARE_DNS1 }}"
      - "{{ VMWARE_DNS2 }}"
  delegate_to: localhost
  tags:
    - vsphere
    - create

- name: Move Virtual Machine
  vmware_guest_move:
    hostname: "{{ VMWARE_HOST }}"
    username: "{{ VMWARE_USER }}"
    password: "{{ VMWARE_PASSWORD }}"
    datacenter: "{{ VMWARE_DATACENTER }}"
    validate_certs: no
    name: "{{ VMWARE_NAME }}"
    dest_folder: "{{ VMWARE_DESTFOLDER }}"
  delegate_to: localhost
  register: facts
  tags:
    - vsphere
    - move
