- name: Install local dependencies
  local_action: command yum -y install python2-pyvmomi

- debug: 
    msg: "were creating a VM for {{ item }}"
  with_items:  "{{ groups['all'] }}" 

- name: Create a virtual machine on given ESXi hostname
  vmware_guest:
    hostname: "192.168.2.2"
    username: "jap680@id.uib.es"
    password: "dddfdffg"
    validate_certs: no
    folder: /DC1/vm/
    name: test_vm_0001_{{ item }}
    state: poweredon
    guest_id: centos64Guest
    # This is hostname of particular ESXi server on which user wants VM to be deployed
    esxi_hostname: "dfdfdff"
    disk:
    - size_gb: 10
      type: thin
      datastore: datastore1
    hardware:
      memory_mb: 512
      num_cpus: 4
      scsi: paravirtual
    networks:
    - name: VM Network
      mac: aa:bb:dd:aa:00:14
      ip: 10.10.10.100
      netmask: 255.255.255.0
      device_type: vmxnet3
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy_vm
  with_items:  "{{ groups['all'] }}"
